language: python
python:
- '3.6'
notifications:
  email: true
services:
- postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE="config.settings.ci"
  matrix:
    secure: UPZsw+X1XHc/uUTXKMhOKnzfoE4gefRzS6UlqRsCnQ7/3SfRZ4QWjBeQWkX70BSuOEqe1AOg6JEy8aKnzN2qlvyG2nUNtOgOwb7jC2v0iSLifi1D8zCZSJl34JmLGkX5WmQh9eJzrPDViAAg/tlw9ArgW0ArMCEG6tiCqlXLl4Oj+g6i4OJKEDQ3exXr29jERiRG01TBDnjLTvi4H96lytk5EglPuG/6rN1vKms0HdMJTvFBXpSpGPeWYPsU9zM2qod4bYx3kFk2ryizLWO/hT5KThi6of6QomMGmm36xDRL76s85i/Km92P5fCjKGArL4tgirelNjopJm/D6dzbpV/DhGqoYSIK3aJ/GUy/EB9kyuz5oBTVYzKwwzbThIWGN68vxUEE0n8aaYX/sFM888oyCIfICPTw8sdVHkBJxRByLin0IjNRiy6azzwwRecV6D7PLGxzIjNkYFvadDwmCEQbmNGIRts+s4RF7g/bk7AJcwtHgOdGgPOjTer8k1++fVRHDY0IyPWF1yYUjuX124EnVw9dpWpF8gqbcPP86HM+nCv2KtT63o2uANiaal3IOn4t4rZMVhQqzsVdglipMTkX8wa8peTypg+enowrqykXFeS8GGYX7/6+Ys+dnSU4Eoi46v4hT3dltBmQYvT1Yu3C5B79XonyyoHVflyiEtc=
before_script:
- psql -c "create database travisci;" -U postgres
install:
- pip install -r requirements.txt
- cd mentorphl/
- python manage.py collectstatic --settings=config.settings.ci
- coverage run --source="." manage.py test --settings=config.settings.ci
- coverage report
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: JsgNqZ/kUGHBFOfDAVJk4L7ynj6YUaMH0kD1ID6JK1CKcGXD31JzsJCoL7KzphAVBCMGy2QHfI3Eoj9DXWAJZqtArRoJvteRCSl1lPTQ08RXk+gXDL1ieCwpx2vKoR9OA16VKPmJOEAEBjVIKWfZEeXuP216I2NXpTjaua/zolCOwD5Jqfcy5bX4ztgeUA4eOti+8tyvzkJLeTwMJe8CqTxkDBr1QMap9wLbNaTGoGEX43hzuMp0UbGwUVzjmcENbvUB/4zFB57/gsB0HW4uIyFtz337QsYJxIn/tDtQZ76oeg6MBP3l58374mFiZTKvon1JOZscmkOb4eTwKHAOHjkamM8xuK2I6d3nOY8aasQAu7l1E1NPURGBCHzcHLkmx9JwZlinoPLBI3JggYVJN6Wz8wouKoEJ6Kln4MhQN5wGS7G/nB0cEP0n2ITMB8amgF7KbCUyia686T08u41i2gkkq1PWWEp5YqgepRh3i0zvrHkg/h62r3ICdW2a5jVAu2OneB/xlzag8kxm4Ep0jCRTD/gAjh0MKECmJgVkR0TSX+XIPeE0VgOQQ/WwDMWUY+QsR2/L3ado81oCbv87yDn+WEZXWwmoW2O3s1+D7NFCgWI3z+nhXE+N55CPRDUXEuDjgY4Asw4N4APD2aJiNyLbcDLVWSHEWnYuPaXBpw8=
  app: mentorphilly
  on:
    repo: zduey/mentorphl
